#!/bin/sh
install=/usr/bin/install
DESTDIR=pkg
prefix=/usr
PREFIX=$prefix
install_prefix=/usr
shpp=shpp
APPNAME=shpp
VER=1.8
TESTFILES=tests/*
# if no sh_make instslled run it with tools/simple_shmake, just make shure that shpp is in $PATH

default() {
 shpp
}

prepare() {
 mkdir -p $DESTDIR/$PREFIX/bin
}

shpp() {
	:
}
install() {
  prepare
  install_shpp

}

tests() {
	load_module shm_local/do_tests
	do_tests $APPNAME   
}
install_shpp() {
	$install shpp $DESTDIR/$PREFIX/bin/shpp
}
installer() {
  load_module configure
  load_module make_installer
  gen_installer > install.sh
}
